= Atto Server
:source-highlighter: rouge
:icons: font

Atto is an Unreal Engine plugin that implements a minimalistic backend / meta service.

IMPORTANT: Atto is not intended for high-load production use.
The goal is to have _a_ meta service for early game development.

Atto aims to be fully compatible with Unreal Engine https://dev.epicgames.com/documentation/en-us/unreal-engine/online-subsystem-in-unreal-engine[Online Subsystems], so you should not need to write Atto-specific code.
If you do have for some reason, either you're using OSS API wrong, or there could be a bug in Atto.
If you're sure it's the latter, consider reporting it to https://github.com/slonopotamus/Atto/issues[Atto issue tracker].

== Dependencies

This project relies on C++20 features.
Tested against Unreal Engine 5.5.

[[features]]
== Features

* Auto-starts in editor, so it is immediately available for PIE
* Provides online subsystem implementation
* Zero cloud dependencies
* Absolutely free and open-source

[[oss]]
== Supported Online Subsystem interfaces

* https://dev.epicgames.com/documentation/en-us/unreal-engine/online-subsystem-identity-interface-in-unreal-engine[Identity] (login, logout)
* https://dev.epicgames.com/documentation/en-us/unreal-engine/online-subsystem-session-interface-in-unreal-engine[Sessions] (create, start, end, destroy, find)
* Time service

== Futher development ideas

* Persistent data storage
* Implement more OSS interfaces
* Add https://dev.epicgames.com/documentation/en-us/unreal-engine/online-services-in-unreal-engine[OnlineServices] implementation
* Add API for game-specific logic

[[command-line]]
== Command-line options

`-DisableAttoServer`:: Disables AttoServer in cases where it would normally start (for example, in editor).

`-EnableAttoServer`:: Enables AttoServer in cases where it would normally not start (for example, game client)

`-AttoListenPort=27777`:: Specifies network port for Atto server

`-AttoBindAddress=0.0.0.0`:: Specifies bind address for Atto server

`-AttoUrl=ws://localhost:27777`:: Specifies Atto server address to connect to

`-AttoPublicAddress=<ip_address>`:: When creating online session, this parameter allows specifying which IP address it will announce for incoming connections

`-AttoPublicPort=<port>`:: When creating online session, this parameter allows specifying which network port it will announce for incoming connections

[[usage]]
== Usage scenario

Suppose, you want to start a separate Atto server, connect one or more dedicated servers to it and one or more game clients.

First, https://dev.epicgames.com/documentation/en-us/unreal-engine/setting-up-dedicated-servers-in-unreal-engine[create client and dedicated server builds of your game].

Now, start Atto server:

[source,shell]
----
$ ./Binaries/<PLATFORM>/<PROJECT_NAME>Server AttoServer -EnableAttoServer -log
----

You may pass <<command-line,additional command-line options>> to configure it.

Verify that Atto server is listening to incoming connections by looking for a relevant log entry:

----
LogAtto: Atto Server started accepting connections on :27777
----

Next, start dedicated server instance:

[source,shell]
----
$ ./Binaries/<PLATFORM>/<PROJECT_NAME>Server <YOUR_GAME_MAP> -log
----

Atto plugin provides a reference `AttoGame` map with `BP_AttoGame` game mode that uses xref:Source/AttoCommon/Public/AttoGameSession.h[AttoGameSession] class.
*AttoGameSession* auto-creates online session when map is loaded and destroys when map is unloaded.
Alternatively, you will need to manage online session in your game code.

You might need to specify `-AttoUrl=...` argument if your Atto server is running on a different machine.

Ensure that dedicated server has properly connected to Atto server and created online session by looking for a relevant entry in dedicated server logs:

----
LogOnline: OSS: Atto server url: ws://localhost:27777
LogOnline: OSS: Created online subsystem instance for: Atto
LogOnline: OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for type [Atto]
...
LogAtto: Creating game session: GameSession
LogAtto: OnCreateSessionComplete GameSession bSuccess: 1
----

Finally, start your game client:

[source,shell]
----
$ ./Binaries/<PLATFORM>/<PROJECT_NAME>
----

You might need to specify `-AttoUrl=...` argument if your Atto server is running on a different machine.

Ensure that client has properly connected to Atto server by looking for a relevant entry in client server logs:

----
LogOnline: OSS: Atto server url: ws://localhost:27777
LogOnline: OSS: Created online subsystem instance for: Atto
LogOnline: OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for type [Atto]
...
LogOnline: OSS: Successfully logged into Atto server, userId=<value>
----

What's next?

You can use https://github.com/mordentral/AdvancedSessionsPlugin[AdvancedSessions] plugin or built-in https://dev.epicgames.com/documentation/en-us/unreal-engine/online-session-nodes?application_version=4.27[Online Subsystem blueprint nodes] or just use OnlineSubsystem from C++.

[[steam]]
== Why not just use Steam OSS?

* Because it doesn't allow to run multiple game instances on the same computer simultaneously
* Because it expects dedicated server to have public IP address
* Because it is nontrivial to run multiple dedicated servers on the same machine
* Because it doesn't work in PIE
